version: '3.5'

# Define services
#
services:
  api-mocker:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app/project
    working_dir: /app/project
    ports:
      - "8080:8080"
    environment:
      docker: "true"

  newman:
    image: postman/newman
    volumes:
      - ./postman_collections:/etc/newman
    command: "run Test_Get_mock.postman_collection.json -e Docker.postman_environment.json"
